In [1]:
from keras.models import load_model

Using TensorFlow backend.


In [2]:
model= load_model('facedetect.h5')

In [3]:
import cv2
import numpy as np
import os
import IPython.display as ipd
import PIL
from keras.preprocessing import image

In [4]:
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')


In [5]:
def face_detector(img, size=0.5):

    # Convert image to grayscale
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    if faces is ():
        return img, []

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h, x:x+w]
        roi = cv2.resize(roi, (224, 224))          #desired format for vgg16
    return img, roi

In [13]:

# Open Webcam
cap = cv2.VideoCapture(0)

while True:

    ret, frame = cap.read()

    image, face = face_detector(frame)
    face=np.array(face)
    face= np.expand_dims(face, axis=0)
    if(face.shape==(1,0)):
        cv2.putText(image, "I don't know", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
        cv2.imshow('Face Recognition', image )
    
    else:
        # Pass face to prediction model
        # "results" comprises of a tuple containing the label and the confidence value
        results = model.predict(face)
        print(results)
        if(results[0][0] == 1.0):
            cv2.putText(image, "sonu", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('Face Recognition', image )

        if(results[0][0] != 1.0):
            cv2.putText(image, "gaurav", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('Face Recognition', image )
            
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()

[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[5.7422803e-22 1.0000000e+00]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[1.9200956e-21 1.0000000e+00]]
[[8.5386866e-08 9.9999988e-01]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
[[0. 1.]]
